### ISSUE TITLE
Plugin is not compatible with the latest commit of snap-plugin-lib-go

### ISSUE THREAD

**Issue by katarzyna-z** [intelsdi-x/snap-plugin-processor-statistics#16]
**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): 4.4.0-42-generic

**What happened**:
Plugin is not compatible with the latest commit of snap-plugin-lib-go, glide.yml does not indicate the proper version of snap-plugin-lib-go.

In [this](https://github.com/intelsdi-x/snap-plugin-lib-go/commit/5b598a38d66bcd799f62fec13756fe424a6532e4) commit,  metric.String() has been removed but this plugin uses it.

Trying to launch small tests with `make test-small`, I'm receiving the following error:
```
2016-10-31 12:45:38 UTC [     info] running test type: small
# github.com/intelsdi-x/snap-plugin-processor-statistics/statistics
statistics/statistics.go:309: metric.Namespace.String undefined (type plugin.namespace has no field or method String)
statistics/statistics.go:327: metric.Namespace.String undefined (type plugin.namespace has no field or method String)
Makefile:29: recipe for target 'test-small' failed
make: *** [test-small] Error 2
```

**Steps to reproduce it** :

1. get the latest version of snap-plugin-lib-go
2. execute make test-small

**Comment by kindermoumoute** [comment]
@katarzyna-z a refactored version of this plugin is coming soon. This will be fixed.
