### ISSUE TITLE
Dynamic metrics should stay dynamic

### ISSUE THREAD

**Issue by katarzyna-z** [intelsdi-x/snap-plugin-processor-statistics#28]
**What happened**:
Dynamic metrics are changed into static metrics.

**What you expected to happen**:
Processor plugin should not change dynamic metrics into static metric (metric without dynamic element).
It is important when user uses InfluxDB publisher. Dynamic elements are moved into tags in InfluxDB, see [this](https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/blob/master/influxdb/influxdb.go#L179).

**Steps to reproduce it** (as minimally and precisely as possible):
1.Load snap-plugin-collector-psutil, snap-plugin-publisher-influxdb, snap-plugin-processor-statistics
2. Create a task using following task manifest to collect dynamic metrics:
```
{
  "version": 1,
  "schedule": {
    "type": "simple",
    "interval": "1s"
  },
  "workflow": {
    "collect": {
      "metrics": {
        "/intel/psutil/net/*/packets_recv": {}
      },
      "process": [
        {
          "plugin_name": "statistics",
          "config": {
            "SlidingWindowLength": 5,
            "SlidingFactor": 2
          },
          "publish": [
            {
              "plugin_name": "influxdb",
              "config": {
                "host": "127.0.0.1",
                "port": 8086,
                "database": "snap-dynamic",
                "user": "admin",
                "password": "admin"
              }
            }
          ]
        }
      ]
    }
  }
```
3. Connect to InfluxDB and see measurements (`SHOW MEASUREMENTS`)
4. Notice that you have set of measurements with name in this form:
```
intel/statistics/intel/psutil/net/eno1/packets_recv/standarddeviation
intel/statistics/intel/psutil/net/eno1/packets_recv/sum
```

It is desired to have measurements with names in following form:
```
intel/statistics/intel/psutil/net/packets_recv/standarddeviation
intel/statistics/intel/psutil/net/packets_recv/sum
```
where `eno1` is moved to tag. InfluxDB publisher is able to publish in this form only if information about dynamic elements is not missed.

**Comment by kindermoumoute** [comment]
@katarzyna-z, can you test #30 to see if it fixes it?
